config/routes.rb
Rails.application.routes.draw do
  

  devise_for :users

  root 'welcome#index'
  resources :users
  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	has_many :comments

	has_attached_file :avatar, :styles => 
	{ :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/ 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

	has_attached_file :avatar, :styles => 
	{ :medium => "300x300>", :thumb => "100x100>" }
	validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/ 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]

 
  def index
    @posts = Post.all
  end

  
  def show
  end

  
  def new
    @post = Post.new
  end

 
  def edit
  end

  
  def create
      @post = Post.new(post_params)
        if @post.save
          redirect_to @post, notice: 'Post was successfully created.'
        else
          render :new 
        end
  end

  
  def update
      if @post.update(post_params)
        redirect_to @post, notice: 'Post was successfully updated.' 
      else
         render :edit 
      end
  end
  
 
  def destroy
    @post.destroy
      redirect_to posts_url, notice: 'Post was successfully destroyed.' 
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:show, :edit, :update, :destroy]
	def index
	@users = User.all
	end

	def show
    end

    def edit
    end

    def update
      if @user.update(user_params)
         redirect_to @user, notice: 'User was successfully updated.' 
      else
        render :edit  
      end
    end

    def destroy
    @user.destroy
      redirect_to users_url, notice: 'User was successfully destroyed.' 
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:email,:password,:avatar)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Devisetest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
</head>
<body>
	<div class="container">	
			<div class="page-header">
				<ul class="nav nav-pills pull-right">
	  				
	  				
      				<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete  %></li>
      				<li><%= link_to"Sign in", new_user_session_path %></li>
      				<li><%= link_to"Sign up", new_user_registration_path %></li>
      				<li><%= link_to "Manage Posts", "/posts"%></li>
      				<li><%= link_to "See Members", "/users" %></li>	

      			</ul>
  				
  				<h1> James Masterson
  				<small>// Palm Beach Executive Chef</small></h1>
	    	</div>
					<p class="notice"><%= notice %></p>
      				<p class="alert"><%= alert %></p>
	    	<div class="row">
	    		<div class="col-md-6 col-md-offset-3">
				<%= yield %>
				</div>
			</div>	
		</div>
	</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_area :content, class: "form-control" %>
  </div>
  <div class="form-group">
  <%= f.label :avatar %><br>
  <%= f.file_field :avatar %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<p>
  <h2><%= link_to post.title, post_path(post) %></h2>
</p>

<p>
  <%= simple_format post.content %>
  
</p>


<%= link_to 'Back', posts_path %>

<p class="text-muted">
	<small>
	Posted on:<%= post.created_at.to_formatted_s(:long) %>
	</small>
</p>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= truncate(post.content, length: 100) %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>
<%= link_to "Home", "/" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if notice.present? %>
	<p class="alert alert-info">
	<%= notice %>
	<p>
<% end %>
 <%= image_tag @post.avatar.url(:thumb) %>
<%= render 'post', post: @post %>
<%= link_to "Home", "/" %>

app/views/users/_form.html.erb
_form.html.erb

<%= form_for (@user),:html => { :multipart => true }  do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
  <%= f.label :avatar %><br>
  <%= f.file_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
edit.html.erb

<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Email</th>
     
     
    
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to "Home", "/" %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<p>
  <strong>Email:</strong>
  <%= @user.email %>
  <%= image_tag @user.avatar.url(:thumb) %>
</p>
<%= link_to "Home", "/" %>

app/views/welcome/index.html.erb
<p><h1>Secret recipes of a Palm Beach Chef</h1>
<br>
As <strong>executive chef of the distinguished Everglades Club and St. Andrews Club, to say James</strong> can look after a million moving pieces would almost be an understatement; with multiple restaurants within the five-star resort, he expertly offers the best of the best. His self-proclaimed "American flare" is evident in his new takes on classics like his lump crab cake with parsnip purée, watercress, Cabernet tomatoes, and balsamic brown butter and internationally inspired dishes, such as tuna tartare and scallop crudo. If it's good enough for the rich and famous, it's good enough for us.
<hr>
<strong>Now James</strong> woukle like to share some insider tips and recipes with you all
</p>